on:
  workflow_call:
    inputs:
      job_name:
        type: string
        required: true
      pr_number:
        type: string
        required: true
    secrets:
      VSCODE_INSTRUCTIONS:
        required: true


jobs:
  update-instructions:
    name: ${{ inputs.job_name }}
    runs-on: ubuntu-latest
    permissions: {}
    env:
      VSCODE_INSTRUCTIONS: ${{ secrets.VSCODE_INSTRUCTIONS }}
      PR_NUMBER: ${{ inputs.pr_number }}
    steps:
      - name: Checkout microsoft/vscode
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          prune-cache: false

      - name: Install dependencies
        run: uv pip install --system jupyter papermill ipykernel python-dotenv requests pandas openai pyjwt cryptography

      - name: Execute notebook
        run: |
          papermill update-instructions.ipynb executed_update_instructions.ipynb --log-output
        working-directory: ./scripts
